server:
  port: 8010
  

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:5555/ms1db
    username: ms1
    password: ms1_abcd
    
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
     
  data:
    rest:
      base-path: /api
      