server:
  port: 8010
  
spring:
  profiles:
    active: dev
    
  mvc:
    servlet:
      path: /ms1

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create
     
  data:
    rest:
      base-path: /api
      
      
---
spring:
  config:
    activate:
      on-profile: dev
      
  datasource:
    url: jdbc:mariadb://localhost:3306/ms1db
    username: ms1
    password: ms1_abcd
    
  jpa:
    show-sql: true
    
---
spring:
  config:
    activate:
      on-profile: prod
      