version: "3.7"
services:
  app:
    build: .
    ports:
      - "9010:8010"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ms1db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ms1
      SPRING_DATASOURCE_PASSWORD: ms1_abcd
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ms1db
      MYSQL_USER: ms1
      MYSQL_PASSWORD: ms1_abcd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /mnt/docker/mariadb/ms1db:/var/lib/mysql
