spring:
  profiles:
    active: dev


server:
  port: 8040
  
---
spring:
  config:
    activate:
      on-profile: dev
  
  cloud:
    stream:
      bindings:
        uppercase-in-0:
          destination: topic.phrase
        uppercase-out-0:
          destination: topic.uppercase
        sourcePhrase-out-0:
          destination: topic.phrase
        sinkPrhase-in-0:
          destination: topic.uppercase
        