server:
  port: 8060
  
logging:
  level:
    '[pe.com.dev4java11]': info

spring:
  application:
    name: ms6
    
  cloud:
    stream:
      source: employee
      function:
        definition: filterGreaterEqualSalary2000;errorFilterGreaterEqualSalary2000
        bindings:
          '[employee-out-0]': empout0
          '[filterGreaterEqualSalary2000-in-0]': fges2000in0
          '[filterGreaterEqualSalary2000-out-0]': fges2000out0
          '[errorFilterGreaterEqualSalary2000-in-0]': efges2000in0
      bindings:
        empout0:
          destination: employee
          producer:
            header-mode: headers
            use-native-encoding: true
        fges2000in0:
          destination: employee
          group: fges2000
          consumer:
            use-native-decoding: true
        fges2000out0:
          destination: fges2000
          producer:
            header-mode: headers
            use-native-encoding: true
        efges2000in0:
          destination: error.employee.fges2000
          group: fges2000
      kafka:
        bindings:
          empout0:
            producer:
              configuration:
                '[topic.replication-factor]': 2
                '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
                '[value.serializer]': org.springframework.kafka.support.serializer.JsonSerializer
          fges2000in0:
            consumer:
              enable-dlq: true
              dlq-producer-properties:
                configuration:
                  '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
                  '[value.serializer]': org.springframework.kafka.support.serializer.JsonSerializer
              configuration:
                '[spring.json.trusted.packages]' : 'pe.com.dev4java11'
                '[key.deserializer]': org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                '[value.deserializer]': org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                '[spring.deserializer.key.delegate.class]': org.apache.kafka.common.serialization.StringDeserializer
                '[spring.deserializer.value.delegate.class]': org.springframework.kafka.support.serializer.JsonDeserializer
          fges2000out0:
            producer:
              configuration:
                '[topic.replication-factor]': 2
                '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
                '[value.serializer]': org.springframework.kafka.support.serializer.JsonSerializer
          efges2000in0:
            consumer:
              configuration:
                '[spring.json.trusted.packages]' : 'pe.com.dev4java11'
                '[key.deserializer]': org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                '[value.deserializer]': org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                '[spring.deserializer.key.delegate.class]': org.apache.kafka.common.serialization.StringDeserializer
                '[spring.deserializer.value.delegate.class]': org.springframework.kafka.support.serializer.JsonDeserializer
        binder:
          brokers:
          - :49159
          - :49160
          - :49161
          auto-add-partitions: true
          replication-factor: 2
          auto-alter-topics: true
          min-partition-count: 3
          configuration:
            '[spring.json.trusted.packages]': '*'
            